// Copyright (c) 2020, RTE (http://www.rte-france.com)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
:icons: font
= Version 1.3.0.RELEASE

== Issue
* [OC-844] Add a UI style for day and a UI style for night with a button to permute. +
This functionality is optional and can be activate/desactivate via configuration +
https://opfab.github.io/documentation/current/deployment/#_web_ui
* [OC-736] Add a field "name" to the object Group

[WARNING]
====
Group data model has changed. +
Please do take a look at the Users API documentation (groups section) :
https://opfab.github.io/documentation/current/api/users/#/groups +
Now, Group data model is : +
[source]
----
Group{
    id*         string
    name        string
    description string
}
----
Please, in the config service, make sure to modify the file users.yml, replacing the field "name" by "id", so that the
Groups objects contain the mandatory field id.
====
* [OC-737] Add an object entity in the user service +
Below, you will find information about our new object "Entity" and its endpoints : +
https://opfab.github.io/documentation/current/api/users/#/entities

* [OC-744] Replace web-ui spring component with Nginx

[NOTE]
====
** adds a new docker configuration for development purpose : `${OF_HOME}/src/main/docker/dev-environment/docker-compose.yml` +
this folder contains also a grayscale version of the favicon. It's helping to distinguish this environment from `deploy` one. +
To force favicon refresh use `CTRL+F5` in the browser. +
Use this configuration when developing on `OperatorFabric` instead of `test-environment` as before.
** removes `keycloak` container from `${OF_HOME}/src/main/docker/test-environment/docker-compose.yml`. +
Clean your docker environment with adding an `--remove-orphans` option to your next `docker-compose` usage.
** removes `container-name`s from `docker-compose.yml` files for `keycloak`, `mongodb` and `rabbitmq` docker service definitions.
====
* [OC-733] As an administrator I would like to be able to customize the icon on the title bar of the browser 

* [OC-876] User Service : Implement group in JWT Token Option
* [OC-402] As an Operator I want the archive screen to display an explicit message if no cards are found that match my filters
* [OC-868] As an admin I would like to be able to hide the time filtrer : https://opfab.github.io/documentation/current/deployment/#_web_ui

== Bugs
* [OC-772] Bug on archives screen: clear results when exiting archive page.
* [OC-775] Card's detail remain displayed when selecting another criteria that doesn't return any result

* [OC-877] User Service : Implement endpoint GET /CurrentUserWithPerimeters

[NOTE]
====
Work is still in progress. The endpoint is not usable at the moment.
====

* [OC-836] Remove netflix stack (eureka registry server) and config server for thirds microservice
* [OC-888] Fix SonarCloud Frontend issues
* [OC-692] Fix SonarCloud Backend issues


